stages:
  - build
  - test

variables:
  MVN: "mvn -B -U -Dmaven.repo.local=m2cache -Pjacoco"
  NG: "node_modules/angular-cli/bin/ng"

.mvn-java-8: &mvn-java-8
  image: maven:3.3-jdk-8-alpine
  tags:
    - docker
  cache:
    key: "mvn-java-8"
    paths:
      - m2cache

.node-6: &node-6
  image: node:6
  tags:
    - docker
  cache:
    key: "node-6"
    paths:
      - frontend/node_modules/

build-backend:
  <<: *mvn-java-8
  stage: build
  script:
    - "$MVN -f backend verify"

build-frontend:
  <<: *node-6
  stage: build
  script:
    - "cd frontend"
    - "npm set progress=false"
    - "npm install"
    - "$NG build"

test-frontend:
  <<: *node-6
  stage: test
  script:
    - "cd frontend"
    - "npm set progress=false"
    - "npm install"
    - "$NG test --watch false"

lint-fronted:
  <<: *node-6
  stage: test
  script:
    - "cd frontend"
    - "npm set progress=false"
    - "npm install"
    - "$NG lint"

