stages:
  - build
  - test
  - package

variables:
  M2_STAGING_DIRECTORY: staging
  M2_CACHED_REPOSITORY: m2cache
  NG: "node_modules/angular-cli/bin/ng"


before_script:
  - "source ci/helpers.sh"

.mvn-java-8: &mvn-java-8
  image: maven:3.3-jdk-8-alpine
  tags:
    - docker
  cache:
    key: "mvn-java-8"
    paths:
      - $M2_CACHED_REPOSITORY

.node-6: &node-6
  image: node:6
  tags:
    - docker
  cache:
    key: "node-6"
    paths:
      - frontend/node_modules/

build-backend:
  <<: *mvn-java-8
  stage: build
  script:
    - "maven-build deploy"
    - "maven-build -f backend deploy"
  artifacts:
    paths:
      - $M2_STAGING_DIRECTORY

build-frontend:
  <<: *node-6
  stage: build
  script:
    - "cd frontend"
    - "npm set progress=false"
    - "npm install"
    - "printenv NG"
    - "$NG build --prod"
    - "$NG lint"
    - "$NG test --watch false"
  artifacts:
    paths:
      - frontend/dist

build-product:
  <<: *mvn-java-8
  stage: package
  dependencies:
    - build-backend
    - build-frontend
  script:
    - "import-staging"
    - "maven -f cockpit package"
  artifacts:
    paths:
      - cockpit/target/petals-cockpit-*-capsule.jar
