stages:
  - build
  - package
  - integration

variables:
  # it is also referenced in ci/settings.xml
  M2_STAGING_DIRECTORY: staging
  M2_CACHED_REPOSITORY: m2cache
  YARN_CACHE_DIRECTORY: yarncache

.mvn-java-8: &mvn-java-8
  image: maven:3.5-jdk-8-alpine
  before_script:
    - source ci/mvn-helpers.sh
  after_script:
    - source ci/mvn-helpers.sh
    - maven ch.ringler.tools:m2cachecleanup:1.0.4:cleanup-cache
  cache:
    key: mvn-java-8
    paths:
      - $M2_CACHED_REPOSITORY

.node-6: &node-java-yarn
  image: registry.gitlab.com/victornoel/node-java-yarn-docker:n6-j8
  before_script:
    # see https://github.com/yarnpkg/yarn/issues/986 or https://github.com/yarnpkg/yarn/issues/988 for optimizing
    - yarn config set cache-folder $PWD/$YARN_CACHE_DIRECTORY --global
    - yarn config set network-concurrency 1
    - du -hs $PWD/$YARN_CACHE_DIRECTORY || true
    - cd frontend
    - export PATH=`yarn bin`:$PATH
    - time yarn --frozen-lockfile --link-duplicates --non-interactive || yarn --frozen-lockfile --link-duplicates --non-interactive
    - du -hs node_modules || true
    - cd ..
  cache:
    key: node-yarn
    paths:
      - $YARN_CACHE_DIRECTORY

pages:
  image: alpine:3.5
  variables:
    GIT_STRATEGY: none
  stage: package
  allow_failure: true
  only:
    - master
  dependencies:
    - build-backend
    - build-frontend
  script:
    - mv frontend-demo public
    - mv backend-apidocs public/apidocs
  artifacts:
    expire_in: 1 day
    paths:
      - public

build-backend:
  <<: *mvn-java-8
  stage: build
  except:
    - /^front\/.*$/
  script:
    # let's lock the version used for SNAPSHOT dependencies to
    # ensure they are the same in the other jobs
    - maven -pl backend -am versions:lock-snapshots
    # deploy to the staging directory
    - maven_build -pl backend -am deploy
    # build the docs
    - maven -pl backend -am com.webcohesion.enunciate:enunciate-slim-maven-plugin:docs && mv backend/target/site/apidocs backend-apidocs || true # this can fail
  artifacts:
    expire_in: 1 week
    paths:
      - backend-apidocs
      - $M2_STAGING_DIRECTORY

build-frontend:
  <<: *node-java-yarn
  stage: build
  except:
    - /^back\/.*$/
  script:
    - cd frontend
    - time yarn run check
    - time yarn run test:ci
    - time ../ci/xrun.sh ../ci/wmrun.sh yarn run e2e:ci
    # build the final frontend for the product
    - time yarn run prod-silent && mv dist ../frontend-dist
    # build the demo for the gitlab pages
    - time yarn run prod-demo && mv dist ../frontend-demo || true # this can fail
  artifacts:
    expire_in: 1 week
    paths:
      - frontend-dist
      - frontend-demo

.build-product: &build-product
  <<: *mvn-java-8
  stage: package
  dependencies:
    - build-backend
    - build-frontend
  script:
    - mv frontend-dist frontend/dist
    - maven dependency:purge-local-repository --non-recursive -DmanualInclude="org.ow2.petals:petals-cockpit-server,org.ow2.petals:petals-cockpit-parent" -DreResolve=false -DsnapshotsOnly=true
    - maven -pl cockpit verify
    - export COCKPIT_VERSION=`ls cockpit/target/petals-cockpit-*-capsule.jar | sed -E 's/.*petals-cockpit-(.*)-capsule.jar/\1/'`
    - export COCKPIT=petals-cockpit-$COCKPIT_VERSION
    - mkdir -p $COCKPIT
    # see https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1664
    - echo $COCKPIT_VERSION > version.txt
    - cp cockpit/target/petals-cockpit-*-capsule.jar $COCKPIT/$COCKPIT.jar
    - cp cockpit/default.yml $COCKPIT/config.yml

release-product:
  <<: *build-product
  only:
    - tags
  artifacts:
    name: petals-cockpit-$(cat version.txt)
    paths:
      - petals-cockpit-*

package-product-master:
  <<: *build-product
  only:
    - master
  artifacts:
    name: petals-cockpit-$(cat version.txt)-${CI_BUILD_REF:0:7}
    paths:
      - petals-cockpit-*

package-product:
  <<: *build-product
  except:
    - master
    - tags
    - /^front\/.*$/
    - /^back\/.*$/
  artifacts:
    expire_in: 1 week
    name: petals-cockpit-$(cat version.txt)-${CI_BUILD_REF:0:7}
    paths:
      - petals-cockpit-*

e2e-product:
  <<: *node-java-yarn
  stage: integration
  except:
    - tags
    - /^front\/.*$/
    - /^back\/.*$/
  dependencies:
    - package-product
    - package-product-master
  variables:
    COCKPIT: java -jar petals-cockpit-*/petals-cockpit-*.jar
    COCKPIT_CONFIG: e2e/default.yml
  script:
    - time $COCKPIT db migrate $COCKPIT_CONFIG --migrations e2e/migrations.xml
    - nohup $COCKPIT server $COCKPIT_CONFIG &
    - cd frontend
    # TODO the exclude does not work, see https://github.com/angular/angular-cli/issues/5172
    - time ../ci/xrun.sh ../ci/wmrun.sh yarn run e2e:product
