stages:
  - build
  - package
  - integration

variables:
  # it is also referenced in ci/settings.xml
  M2_STAGING_DIRECTORY: staging
  M2_CACHED_REPOSITORY: m2cache
  YARN_CACHE_DIRECTORY: yarncache
  DISPLAY: ":99"
  XVFB: "Xvfb $DISPLAY -ac -screen 0 1920x1080x24 -nolisten tcp"

.mvn-java-8: &mvn-java-8
  image: maven:3.3-jdk-8-alpine
  before_script:
    - "source ci/mvn-helpers.sh"
  after_script:
    - "source ci/mvn-helpers.sh"
    - "maven ch.ringler.tools:m2cachecleanup:1.0.4:cleanup-cache"
  cache:
    key: "mvn-java-8"
    paths:
      - $M2_CACHED_REPOSITORY

.node-6: &node-java-yarn
  image: registry.gitlab.com/victornoel/node-java-yarn-docker:n7-j8-y0.18
  before_script:
    # see https://github.com/yarnpkg/yarn/issues/986 or https://github.com/yarnpkg/yarn/issues/988 for optimizing
    - "yarn config set cache-folder $PWD/$YARN_CACHE_DIRECTORY --global"
    - "cd frontend"
    - "export PATH=`yarn bin`:$PATH"
    # see https://github.com/yarnpkg/yarn/issues/1682 for segfault problems (hence the ||)
    - "time yarn --pure-lockfile || yarn --pure-lockfile"
    - "cd .."
  cache:
    key: "node-yarn"
    paths:
      - $YARN_CACHE_DIRECTORY

pages:
  <<: *node-java-yarn
  stage: package
  script:
    - "cd frontend"
    - "ng build --prod -e=gitlab-pages -bh=/petals-cockpit/"
    - "mv dist ../public"
  artifacts:
    paths:
      - public
  allow_failure: true
  only:
    - master

build-backend:
  <<: *mvn-java-8
  stage: build
  except:
    - /^front\/.*$/
  script:
      # let's lock the version used for SNAPSHOT dependencies to
      # ensure they are the same in the other jobs
    - "maven -pl backend -am versions:lock-snapshots"
    - "maven_build -pl backend -am deploy"
  artifacts:
    paths:
      - $M2_STAGING_DIRECTORY

build-frontend:
  <<: *node-java-yarn
  stage: build
  except:
    - /^back\/.*$/
  script:
    - "cd frontend"
    - "time ng lint"
    - "time node generate-headers.js --dry"
    - "nohup $XVFB &"
    - "XVFBPID=$!"
    - "time ng test --watch false"
    - "nohup ng serve -e=prod-e2e &"
    - "NGPID=$!"
    - "time ng e2e"
    - "kill $NGPID"
    - "kill $XVFBPID"
    - "time ng build --prod"
  artifacts:
    paths:
      - frontend/dist

build-product:
  <<: *mvn-java-8
  stage: package
  except:
    - /^front\/.*$/
    - /^back\/.*$/
  dependencies:
    - build-backend
    - build-frontend
  script:
    - 'maven dependency:purge-local-repository --non-recursive -DmanualInclude="org.ow2.petals:petals-cockpit-server,org.ow2.petals:petals-cockpit-parent" -DreResolve=false -DsnapshotsOnly=true'
    - "maven -pl cockpit verify"
    - export VC=`ls cockpit/target/petals-cockpit-*-capsule.jar | sed -E 's/.*petals-cockpit-(.*)-capsule.jar/\1/'`
    - "mkdir -p dist/$VC"
    - "cp cockpit/target/petals-cockpit-*-capsule.jar dist/$VC/petals-cockpit.jar"
    - "cp cockpit/default.yml dist/$VC/config.yml"
  artifacts:
    paths:
      - dist/

e2e-product:
  <<: *node-java-yarn
  stage: integration
  only:
    - master
    - integration
    - /^product\/.*$/
  dependencies:
    - build-product
  variables:
    COCKPIT: "java -jar dist/*/petals-cockpit.jar"
    COCKPIT_CONFIG: "e2e/default.yml"
  script:
    - "$COCKPIT db migrate $COCKPIT_CONFIG --migrations e2e/migrations.xml"
    - "nohup $COCKPIT server $COCKPIT_CONFIG &"
    - "nohup $XVFB &"
    - "cd frontend"
    - yarn run e2e -- --exclude "e2e/*needspetals*.ts"
