stages:
  - build
  - package
  - integration

variables:
  # it is also referenced in ci/settings.xml
  M2_STAGING_DIRECTORY: staging
  M2_CACHED_REPOSITORY: m2cache
  YARN_CACHE_DIRECTORY: yarncache
  DISPLAY: ":99"
  XVFB: Xvfb $DISPLAY -ac -screen 0 1920x1080x24 -nolisten tcp

.mvn-java-8: &mvn-java-8
  image: maven:3.3-jdk-8-alpine
  before_script:
    - source ci/mvn-helpers.sh
  after_script:
    - source ci/mvn-helpers.sh
    - maven ch.ringler.tools:m2cachecleanup:1.0.4:cleanup-cache
  cache:
    key: mvn-java-8
    paths:
      - $M2_CACHED_REPOSITORY

.node-6: &node-java-yarn
  image: registry.gitlab.com/victornoel/node-java-yarn-docker:n6-j8-y0.21
  before_script:
    # see https://github.com/yarnpkg/yarn/issues/986 or https://github.com/yarnpkg/yarn/issues/988 for optimizing
    - yarn config set cache-folder $PWD/$YARN_CACHE_DIRECTORY --global
    # see https://github.com/yarnpkg/yarn/issues/2629
    - yarn config set network-concurrency 2 --global
    - du -hs $PWD/$YARN_CACHE_DIRECTORY || true
    - cd frontend
    - export PATH=`yarn bin`:$PATH
    - time yarn --frozen-lockfile --link-duplicates
    - du -hs node_modules || true
    - cd ..
  cache:
    key: node-yarn
    paths:
      - $YARN_CACHE_DIRECTORY

pages:
  image: alpine:3.5
  variables:
    GIT_STRATEGY: none
  stage: package
  allow_failure: true
  only:
    - master
  dependencies:
    - build-backend
    - build-frontend
  script:
    - mv frontend-demo public
    - mv backend-apidocs public/apidocs
  artifacts:
    paths:
      - public

build-backend:
  <<: *mvn-java-8
  stage: build
  except:
    - /^front\/.*$/
  script:
    # let's lock the version used for SNAPSHOT dependencies to
    # ensure they are the same in the other jobs
    - maven -pl backend -am versions:lock-snapshots
    # deploy to the staging directory
    - maven_build -pl backend -am deploy
    # build the docs
    - maven -pl backend -am com.webcohesion.enunciate:enunciate-slim-maven-plugin:docs && mv backend/target/site/apidocs backend-apidocs || true # this can fail
  artifacts:
    paths:
      - backend-apidocs
      - $M2_STAGING_DIRECTORY

build-frontend:
  <<: *node-java-yarn
  stage: build
  except:
    - /^back\/.*$/
  script:
    - cd frontend
    - time ng lint
    - time node generate-headers.js --dry
    - nohup $XVFB &
    - XVFBPID=$!
    - time ng test --progress=false --single-run --code-coverage
    - time ng e2e --prod --progress=false -e=prod-e2e
    - kill $XVFBPID
    # build the final frontend for the product
    - time yarn run prod-silent && mv dist ../frontend-dist
    # build the demo for the gitlab pages
    - time yarn run prod-demo && mv dist ../frontend-demo || true # this can fail
  artifacts:
    paths:
      - frontend-dist
      - frontend-demo

build-product:
  <<: *mvn-java-8
  stage: package
  except:
    - /^front\/.*$/
    - /^back\/.*$/
  dependencies:
    - build-backend
    - build-frontend
  script:
    - mv frontend-dist frontend/dist
    - maven dependency:purge-local-repository --non-recursive -DmanualInclude="org.ow2.petals:petals-cockpit-server,org.ow2.petals:petals-cockpit-parent" -DreResolve=false -DsnapshotsOnly=true
    - maven -pl cockpit verify
    - export VC=`ls cockpit/target/petals-cockpit-*-capsule.jar | sed -E 's/.*petals-cockpit-(.*)-capsule.jar/\1/'`
    - mkdir -p dist/$VC
    - cp cockpit/target/petals-cockpit-*-capsule.jar dist/$VC/petals-cockpit.jar
    - cp cockpit/default.yml dist/$VC/config.yml
  artifacts:
    paths:
      - dist

e2e-product:
  <<: *node-java-yarn
  stage: integration
  only:
    - master
    - integration
    - /^product\/.*$/
  dependencies:
    - build-product
  variables:
    COCKPIT: java -jar dist/*/petals-cockpit.jar
    COCKPIT_CONFIG: e2e/default.yml
  script:
    - time $COCKPIT db migrate $COCKPIT_CONFIG --migrations e2e/migrations.xml
    - nohup $COCKPIT server $COCKPIT_CONFIG &
    - nohup $XVFB &
    - cd frontend
    # TODO the exclude does not work, see https://github.com/angular/angular-cli/issues/5172
    - time ng e2e --serve=false --specs=e2e/login.e2e-spec.ts --specs=e2e/workspaces.e2e-spec.ts --specs=e2e/workspace-tree.e2e-spec.ts
