stages:
  - build
  - test
  - package

variables:
  M2_STAGING_DIRECTORY: staging
  M2_CACHED_REPOSITORY: m2cache
  NG: "node_modules/angular-cli/bin/ng"

.mvn-java-8: &mvn-java-8
  image: maven:3.3-jdk-8-alpine
  before_script:
    - "source ci/mvn-helpers.sh"
  after_script:
    - "source ci/mvn-helpers.sh"
    - "maven ch.ringler.tools:m2cachecleanup:1.0.4:cleanup-cache"
  tags:
    - docker
  cache:
    key: "mvn-java-8"
    paths:
      - $M2_CACHED_REPOSITORY

.node-6: &node-6
  image: node:6
  before_script:
    - "npm set -g progress=false"
    - "cd frontend"
    - "npm install"
    - "printenv NG"
    - "$NG -v"
    - "cd .."
  tags:
    - docker
  cache:
    key: "node-6"
    paths:
      - frontend/node_modules/

build-backend:
  <<: *mvn-java-8
  stage: build
  script:
    - "maven_build -pl backend -am deploy"
  artifacts:
    paths:
      - $M2_STAGING_DIRECTORY

build-frontend:
  <<: *node-6
  stage: build
  script:
    - "cd frontend"
    - "$NG build --prod"
    - "$NG lint"
    - "$NG test --watch false"
  artifacts:
    paths:
      - frontend/dist

build-product:
  <<: *mvn-java-8
  stage: package
  dependencies:
    - build-backend
    - build-frontend
  script:
    - "import_staging"
    - "maven -pl cockpit package"
  artifacts:
    paths:
      - cockpit/target/petals-cockpit-*-capsule.jar
