# configuration for dropwizard
---
server:
  # only http on 8080
  type: simple
  # the backend will be served via /api on 8080
  rootPath: /api
  applicationContextPath: /
  # the admin console is served via /admin on 8080 (do not do this in production!)
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

# configuration to connect to mongo
mongo:
  database: petalscockpit
  servers:
    - host: localhost
      port: 27017

logging:
  level: INFO
  loggers:
    org.pac4j: DEBUG
    org.ow2.petals.cockpit: DEBUG
