# configuration for dropwizard
---
server:
  # the backend will be served via /api on 8484
  rootPath: /api
  # the frontend will be served via / on 8484
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 4200
  # the admin console will be served via / on 8082
  adminContextPath: /
  adminConnectors:
    - type: http
      port: 8082
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./e2e/logs/cockpit-e2e-run.requests.log
        archivedLogFilenamePattern: ./e2e/logs/cockpit-e2e-run.%d.requests.gz

database:
  driverClass: org.h2.Driver
  user: petals
  password: petals
  url: jdbc:h2:./e2e/cockpit
  # see http://stackoverflow.com/a/3670000
  validationQuery: "/* Health Check */ SELECT 1"

logging:
#Global logging setting
  level: INFO

#Specific cockpit loggers settings
#(will bypass the console threshold & filter)
  loggers:
    "org.ow2.petals.cockpit.server":
      level: INFO
      appenders:
        - type: console

#File logging uses global setting, console filters out global cockpit output
#(to avoid duplicates from previous specific logger)
  appenders:
    - type: file
      currentLogFilename: ./e2e/logs/cockpit-e2e-run.global.log
      archivedLogFilenamePattern: ./e2e/logs/cockpit-e2e-run.%d.log.gz
    - type: console
      threshold: WARN
      filterFactories:
      - type: cockpit-server-filter-factory
