# configuration for dropwizard
---
server:
  # the backend will be served via /api on 8080
  # note: this is relative to applicationContextPath
  rootPath: /api
  # the frontend will be served via / on 8080
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  # the admin console will be served via / on 8082
  adminContextPath: /
  # but we disable it by default
  adminConnectors: []
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/cockpit-access.log
        archivedLogFilenamePattern: ./logs/cockpit-access-%d.log.gz

database:
  driverClass: org.h2.Driver
  user: petals
  password: petals
  url: jdbc:h2:./db/cockpit
  # see http://stackoverflow.com/a/3670000
  validationQuery: "/* Health Check */ SELECT 1"

logging:
  level: INFO
  loggers:
    org.ow2.petals.cockpit.CockpitApplication:
      appenders:
        - type: console
          threshold: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/cockpit.log
      archivedLogFilenamePattern: ./logs/cockpit-%d.log.gz
      archivedFileCount: 5
    - type: console
      threshold: WARN
