# configuration for dropwizard
---
server:
  # the backend will be served via /api on 8484
  # note: this is relative to applicationContextPath
  rootPath: /api
  # the frontend will be served via / on 8484
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8484
  # the admin console will be served via / on 8082
  adminContextPath: /
  # but we disable it by default
  adminConnectors: []
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/cockpit-access.log
        archivedLogFilenamePattern: ./logs/cockpit-access-%d.log.gz

database:
  driverClass: org.h2.Driver
  user: petals
  password: petals
  url: jdbc:h2:./db/cockpit
  # see http://stackoverflow.com/a/3670000
  validationQuery: "/* Health Check */ SELECT 1"

logging:
#Global logging setting
  level: INFO

#Specific cockpit loggers settings
#(will bypass the console threshold & filter)
  loggers:
    "org.ow2.petals.cockpit.server":
      level: INFO
      appenders: 
        - type: console

#File logging uses global setting, console filters out global cockpit output
#(to avoid duplicates from previous specific logger)
  appenders:
    - type: file
      currentLogFilename: ./logs/cockpit.log
      archivedLogFilenamePattern: ./logs/cockpit-%d.log.gz
      archivedFileCount: 5
    - type: console
      threshold: WARN
      filterFactories:
      - type: cockpit-server-filter-factory

# Uncomment and fill this section to use LDAP authentication
#ldapConfig:
#  url: ldap://X.X.X.X:Y
#  usersDn: ou=personnes,dc=my-domain,dc=com
#  usernameAttribute: mandatory username ldap attribute (eg. uid)
#  nameAttribute: optionnal name ldap attribute (eg. cn)
#  passwordAttribute: optionnal password ldap attribute (eg. password)
#  principalDn: principal account dn (eg. uid=admin,ou=personnes,dc=my-domain,dc=com)
#  principalPassword: principal account password (eg. azerty123)
