# configuration for dropwizard
---
server:
  # the backend will be served via /api on 8080
  rootPath: /api
  # the frontend will be served via / on 8080
  applicationContextPath: /
  # the admin console is served via / on 8082
  adminContextPath: /
  adminConnectors:
    - type: http
      port: 8082

# configuration to connect to mongo
mongo:
  database: petalscockpit
  servers:
    - host: localhost
      port: 27017

logging:
  level: INFO

pac4j:
