# configuration for dropwizard
---
server:
  type: simple
  # the backend will be served via /api
  rootPath: /api
  # the frontend will be served via /
  applicationContextPath: /
  # the admin console is served via /admin (note: do not do this in production)
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

# configuration to connect to mongo
mongo:
  database: petalscockpit
  servers:
    - host: localhost
      port: 27017

logging:
  level: INFO

