# configuration for dropwizard
---
server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 7203

# configuration to connect to mongo
mongo:
  database: petalscockpit
  servers:
    - host: localhost
      port: 27017

logging:
  level: INFO